### PR TITLE
Implement style lining

### PR DESCRIPTION
**Pull request by Bartekus**

### CODE REVIEW

**Comment by jtmthf** [comment]
@Bartekus Do you have any lint errors showing up after adding `stylelint`? I implemented in this in a fork a few days back and had to add [stylelint-config-css-modules](https://github.com/pascalduez/stylelint-config-css-modules) to get the css to parse. Also I found a few small areas where this project's css doesn't match the stylelint standard config which would need to be addressed as well.

**Comment by Bartekus** [comment]
@jtmthf I've retested everything with the current version of the kit and everything is working fine so no errors are showing up with this implementation.

**Comment by leebenson** [comment]
Apologies for taking so long to respond on this PR @Bartekus. I've never used this plugin, so before I merge this in, I'd like to address the point @jtmthf made above re: some adjustments that were needed to make this fit with the current config.

Is this still the case, or does it now work as per the PR?

Also, do you know if this will interfere with .less files, or will it ignore everything that's not .css and .scss?

**Comment by leebenson** [comment]
I'll go ahead and close this for now -- feel free to re-submit if the above feedback is resolved.

**Pull request closed without merging**
