### PR TITLE
Optimize Dockerfile

### PR DESCRIPTION
**Pull request by kane-c**
Switch to Node/Alpine base image instead of Debian - makes for a much smaller Docker image.

Also add `package-lock.json` to the build and optimize order of commands for a quicker build.

### CODE REVIEW

**Comment by noeljackson** [comment]
Have the node-sass issues with node on alpine based images been resolved? https://github.com/sass/node-sass/issues/2031

**Comment by leebenson** [comment]
might need to add the fix from https://github.com/jubel-han/dockerfiles/blob/master/node/Dockerfile - haven't tested yet

**Comment by leebenson** [comment]
node-sass seems to work perfectly from first testing.

Unrelated, I made one slight change to how `package(-lock).json` is being pulled in:

```
ADD package*.json .
```

Just to avoid an error in the event that `package-lock.json` is missing, and/or hasn't yet been built in a project.

This Alpine-based image may cause issues for third-party/additional binary NPM packages that are incompatible for musl libc, but I'd consider that an edge case that probably warrants the developer writing their own Dockerfile anyway.

Nice size savings - 323mb vs 943mb for the previous, and 271mb+ of that is the compiled `node_modules` 👍  - thanks @kane-c, will get this in the next release.

**Comment by kane-c** [comment]
Awesome, happy to help!

**Comment by arsanjea** [comment]
This is creating problems for me on a very simple app btw. Trying to fix it with a workaround.

**Comment by kane-c** [comment]
What sort of problems?

**Comment by arsanjea** [comment]
This kind:
https://github.com/reactql/kit/issues/114

*-------------------------------------*
*Jean-Marc Arsan*
Founder & CTO @ MoneyGoat <https://www.goat.money/>
79 Madison Avenue, Suite 55
<https://maps.google.com/?q=79+Madison+Avenue,+Suite+55New+York,+NY,+10016&entry=gmail&source=g>
New York, NY, 10016
<https://maps.google.com/?q=79+Madison+Avenue,+Suite+55New+York,+NY,+10016&entry=gmail&source=g>

phone: +1 (310) 435-9983
email: jm@Goat.Money

**Comment by leebenson** [comment]
This, like any starter kit/framework `Dockerfile`, won't work in every situation. If you're straying from the out-the-box defaults and adding binaries, you'll probably run into edge cases / things that are broken sooner or later. That's especially true since we're using an Alpine base, which uses musl libc and may not run everything designed for glibc.

This is only intended to be a starter template, designed mostly to strike a decent enough balance between build speed, caching, and the size of the resulting image. You're encouraged to tweak for your project's production requirements.

**Pull request merged**
