### PR TITLE
Added needed Jest config to babel and eslint

### LINKED ISSUE #81: how to configure with jest
I see jest in package.json but it seems there's a bit more config needed to be able to use it to test React components.  Any plans to add that either in kit or an example?

### PR DESCRIPTION
**Pull request by nate0001**
fixes #81

### CODE REVIEW

**Comment by caedmon** [comment]
This does indeed get it closer to working, thanks.

I also had to add to .babelrc:
  "plugins": ["transform-class-properties", "transform-object-rest-spread"],
I suppose the list should match those in the webpack config files.

And I still get the 'React depends on requestAnimationFrame.' warning.

To get coverage of untested files, I also had to add a jest.conf.js excluding dist and kit as well as the usual node_modules.

**Comment by nate0001** [comment]
@caedmon Can you post your jest config? I'll add to the PR.

**Comment by caedmon** [comment]
Not sure what's the best way to post the file, but maybe this will work.
I ended up setting it up to report coverage only for src, so no need to exclude dist, kit and node_modules.

[jest.config.js.txt](https://github.com/reactql/kit/files/1335731/jest.config.js.txt)

**Comment by leebenson** [comment]
@nate0001 - I'll leave this PR open, pending your comments on @caedmon's config changes. If that completes the jest testing config, feel free to re-commit and I'll merge.

**Comment by caedmon** [comment]
I wonder if it wouldn't be helpful to include a sample test of a component and/or some mention in the doc of how to add a test and run tests.

**Comment by nate0001** [comment]
Fixed babelrc and jest config.

**Comment by nate0001** [comment]
Actually this doesn't work.

**Comment by nate0001** [comment]
I've modified the jest.config.js and added jest.transform.js

This fixes the babel errors. I still don't have module path aliases working yet.

**Comment by nate0001** [comment]
Fixed the babel errors by installing `babel-jest`. There's still the issue of import aliases.

**Comment by nate0001** [comment]
Fixed import aliases.

Everything should be working correctly now

**Comment by caedmon** [comment]
I added #112 to fix one problem I found with this config.  Another problem I'm seeing is with babel config where in some cases it throws on destructuring assignment.  I can silence that by changing the jest.transform.js to look like this:
  presets: [
    'react',
    ['env']
  ],
However, I'm not terribly familiar with babel config and not sure if that could introduce other problems.

**Pull request merged**
